// Historical events extracted from WhatsApp group chat
// All events before 9/5/2026 (excluding 9-10 May 2026 current events)

interface HistoricalEvent {
  nama_majlis: string
  hall_name: string
  tarikh: Date
  sesi: 'siang' | 'malam'
  pax: number
  status: 'completed'
  menu_selection: {
    nasi: string
    ayam: string
    daging: string
    acar: string
    bubur: string
    air_panas: string
  }
  remarks?: string
  // Invoice data
  invoice: {
    line_items: Array<{description: string, qty: number, unit_price: number}>
    gaji_pekerja: number
    berkat: number
  }
}

// Standard menu (default when not specified)
const STD = {
  nasi_briyani: 'Nasi Briyani',
  nasi_minyak: 'Nasi Minyak',
  ayam: 'Ayam Masak Merah',
  daging_hitam: 'Daging Masak Hitam',
  daging_briyani: 'Daging Briyani',
  daging_kuzi: 'Daging Kuzi',
  paceri: 'Paceri Nenas',
  pencuk: 'Pencuk',
  pulut: 'Bubur Pulut Hitam',
  kacang: 'Bubur Kacang Hijau',
  teh: 'Teh O',
  kopi: 'Kopi O',
}

// Gaji pekerja lookup
function gajiLookup(pax: number): number {
  if (pax <= 300) return 530
  if (pax <= 400) return 590
  if (pax <= 500) return 850
  if (pax <= 650) return 910
  if (pax <= 700) return 970
  if (pax <= 800) return 1030
  if (pax <= 1000) return 1150
  if (pax <= 1300) return 1680
  return 2000
}

// Berkat lookup
function berkatLookup(pax: number): number {
  if (pax <= 500) return 100
  if (pax <= 800) return 200
  return 300
}

// Invoice builder
function buildInvoice(pax: number, hall: string, extraItems?: Array<{desc: string, qty: number, price: number}>) {
  const items = [
    { description: `Katering — ${hall} — ${pax} pax`, qty: pax, unit_price: 10 },
    { description: 'Makan Beradab', qty: 1, unit_price: 100 },
    { description: 'Berkat', qty: 1, unit_price: berkatLookup(pax) },
    ...(extraItems?.map(i => ({ description: i.desc, qty: i.qty, unit_price: i.price })) || [])
  ]
  return {
    line_items: items,
    gaji_pekerja: gajiLookup(pax),
    berkat: berkatLookup(pax)
  }
}

export const historicalEvents: HistoricalEvent[] = [
  // ── NOVEMBER 2024 ──────────────────────────────────────────
  {
    nama_majlis: 'Majlis Amirul & Hana',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2024-11-23'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    remarks: 'Cendol, putu bambu, pancake, laksa johor 300pax (tuan rumah)',
    invoice: buildInvoice(1000, 'Juwita Hall'),
  },

  // ── DECEMBER 2024 ─────────────────────────────────────────
  {
    nama_majlis: 'Majlis 7 Dis (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2024-12-07'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis 7 Dis (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2024-12-07'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis 15 Dis (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2024-12-15'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Adila (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2024-12-21'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Syafika (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2024-12-21'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Hazlan (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2024-12-22'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Juwita Hall'),
  },

  // ── JANUARY 2025 ──────────────────────────────────────────
  {
    nama_majlis: 'Majlis Norliyana (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-01-04'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis 30 Jan (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-01-30'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Syahirah Nabila (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-01-25'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Aisyah & Nazreen (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-01-26'),
    sesi: 'siang',
    pax: 300,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(300, 'Elham Hall'),
  },

  // ── FEBRUARY 2025 ─────────────────────────────────────────
  {
    nama_majlis: 'Majlis 31 Jan (Elham Malam)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-01-31'),
    sesi: 'malam',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Azua (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-02-01'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis 1 Feb (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-02-01'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis 2 Feb (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-02-02'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis 2 Feb Siang (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-02-02'),
    sesi: 'siang',
    pax: 300,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(300, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis 2 Feb Malam (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-02-02'),
    sesi: 'malam',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Nakyrah (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-02-16'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis 22 Feb (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-02-22'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Mica & Zizi (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-02-23'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Juwita Hall'),
  },

  // ── APRIL 2025 ────────────────────────────────────────────
  {
    nama_majlis: 'Majlis 12 Apr (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-04-12'),
    sesi: 'siang',
    pax: 800,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(800, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis 12 Apr (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-04-12'),
    sesi: 'siang',
    pax: 600,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(600, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis 13 Apr (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-04-13'),
    sesi: 'siang',
    pax: 550,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(550, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Hawa & Asyraf (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-04-19'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis 19 Apr (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2025-04-19'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Asmara Hall'),
  },

  // ── MAY 2025 ──────────────────────────────────────────────
  {
    nama_majlis: 'Majlis Eleysia Farhany (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-05-18'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis 18 Mei (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-05-18'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Hamdi & Syafiqah (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-05-24'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Rekha (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2025-05-31'),
    sesi: 'siang',
    pax: 300,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(300, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Fika & Endi (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-05-31'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Juwita Hall'),
  },

  // ── JUNE 2025 ─────────────────────────────────────────────
  {
    nama_majlis: 'Majlis Pieja & Fendi (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-06-01'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Hisyam (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-06-08'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Nurin & Haziq (Asmara Malam)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2025-06-14'),
    sesi: 'malam',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Isz (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-06-21'),
    sesi: 'siang',
    pax: 650,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(650, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Syahida & Raziz (Asmara Malam)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2025-06-21'),
    sesi: 'malam',
    pax: 300,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(300, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Nessa & Syawal (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-06-22'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Afiqah (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-06-22'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Ain Izaty & Hafiz (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2025-06-28'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Asmara Hall'),
  },

  // ── JULY 2025 ─────────────────────────────────────────────
  {
    nama_majlis: 'Majlis Hafiq & Zura (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-07-06'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Qimi & Effa (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-07-06'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis 13 Jul (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-07-13'),
    sesi: 'siang',
    pax: 600,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(600, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis 13 Jul (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-07-13'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Shafie & Amira (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-07-20'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Ain & Amirul (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-07-20'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Noorsuraini & Zairi (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-07-27'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Juwita Hall'),
  },

  // ── AUGUST 2025 ───────────────────────────────────────────
  {
    nama_majlis: 'Majlis Shamira & Izammudin (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-08-02'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis 16 Ogos (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-08-16'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis 24 Ogos (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-08-24'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Dayang & Nazmi (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-08-30'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Dayana & Firdaus (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-08-31'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Sheila & Syafiq (Elham Malam)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-08-31'),
    sesi: 'malam',
    pax: 300,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(300, 'Elham Hall'),
  },

  // ── SEPTEMBER 2025 ────────────────────────────────────────
  {
    nama_majlis: 'Majlis Nazurah & Ammar (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-09-06'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Aisyah & Iqmal (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2025-09-07'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Insyirah & Shafiq (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-09-16'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Anis & Ramzi (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2025-09-21'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Hidayah & Harith (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2025-09-27'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis 28 Sep (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-09-28'),
    sesi: 'siang',
    pax: 400,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(400, 'Juwita Hall'),
  },

  // ── OCTOBER 2025 ──────────────────────────────────────────
  {
    nama_majlis: 'Majlis Aqil & Sarah (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-10-05'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis 11 Okt (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-10-11'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Aisyah Arina (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-10-12'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Nadzirah & Faizal (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2025-10-12'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis 18 Okt (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-10-18'),
    sesi: 'siang',
    pax: 1200,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1200, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Ali & Rosdiana (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2025-10-19'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Sabrina & Hakim (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-10-19'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Suraya & Hazim (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-10-25'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis 25 Okt Malam (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-10-25'),
    sesi: 'malam',
    pax: 300,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(300, 'Juwita Hall'),
  },

  // ── NOVEMBER 2025 ─────────────────────────────────────────
  {
    nama_majlis: 'Majlis Sherena & Saiful (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-11-01'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Puteri & Naim (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-11-01'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Anis & Nazmee (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-11-02'),
    sesi: 'siang',
    pax: 1300,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1300, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis 2 Nov (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-11-02'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Indah (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-11-08'),
    sesi: 'siang',
    pax: 300,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(300, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis 9 Nov (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-11-09'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Sabrina & Fakhri (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2025-11-09'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Zulaikha & Daniel (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-11-15'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis 15 Nov (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-11-15'),
    sesi: 'siang',
    pax: 800,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(800, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Shaa & Mukhriss (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2025-11-15'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Aina & Fahmi (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-11-22'),
    sesi: 'siang',
    pax: 300,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(300, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Sara & Amirul (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-11-23'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Zaqeerah (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-11-23'),
    sesi: 'malam',
    pax: 300,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(300, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Syafwani & Iman (Elham Malam)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-11-29'),
    sesi: 'malam',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Norfarahana & Syafiq (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2025-11-29'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Safika & Zulfahmi (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-11-29'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Nadia & Said (Asmara Malam)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2025-11-29'),
    sesi: 'malam',
    pax: 300,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(300, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis 30 Nov (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-11-30'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Juwita Hall'),
  },

  // ── DECEMBER 2025 ─────────────────────────────────────────
  {
    nama_majlis: 'Majlis Ayu & Hakim (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2025-12-06'),
    sesi: 'siang',
    pax: 300,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(300, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Izah & Fikri (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2025-12-07'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Haiza & Daniel (Asmara Malam)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2025-12-13'),
    sesi: 'malam',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Syahirah & Daneal (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-12-13'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Wani & Syafiq (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-12-14'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Dewi & Haziq (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-12-14'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Nasruddin & Anis (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2025-12-20'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Aqila & Naziri (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-12-21'),
    sesi: 'siang',
    pax: 300,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(300, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Nurin & Fauzan (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-12-25'),
    sesi: 'siang',
    pax: 300,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(300, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Zainab & Nuh (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-12-25'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Nisa & Zul (Elham Malam)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-12-26'),
    sesi: 'malam',
    pax: 300,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(300, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Shahira & Aiman (Juwita Malam)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-12-27'),
    sesi: 'malam',
    pax: 400,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(400, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Afiqah & Shazwan (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2025-12-28'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Rina & Aiman (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2025-12-28'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Juwita Hall'),
  },

  // ── JANUARY 2026 ──────────────────────────────────────────
  {
    nama_majlis: 'Majlis Syahira & Zulhusni (Asmara Malam)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2026-01-03'),
    sesi: 'malam',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_minyak, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Nasuhah & Afiq (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2026-01-04'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Helmi & Aina (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2026-01-04'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Natasha & Firdaus (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2026-01-04'),
    sesi: 'malam',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Nisa & Syazwan (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2026-01-04'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Syurah & Azmir (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2026-01-10'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Syifa & Ikmal (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2026-01-10'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Zarifah & Akmal (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2026-01-11'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Nasri & Khadeeja (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2026-01-11'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Desy & Haikal (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2026-01-17'),
    sesi: 'siang',
    pax: 300,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(300, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Kaiyisah & Muadzam (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2026-01-17'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Izzati & Azri (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2026-01-17'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Nadzirah & Shahrul (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2026-01-24'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Ireka & Haziq (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2026-01-25'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Afifah & Amin (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2026-01-31'),
    sesi: 'siang',
    pax: 300,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(300, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Afiqah & Amyrul (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2026-01-31'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Juwita Hall'),
  },

  // ── FEBRUARY 2026 ─────────────────────────────────────────
  {
    nama_majlis: 'Majlis Aida & Faiz (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2026-02-01'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Fatin & Danial (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2026-02-01'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Zulhilmi & Intan (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2026-02-07'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Fariesya & Izz (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2026-02-07'),
    sesi: 'malam',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Lukman & Shahimah (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2026-02-07'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Aina & Amin (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2026-02-07'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Ayu & Fendi (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2026-02-07'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Hasrin & Luqman (Elham Malam)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2026-02-07'),
    sesi: 'malam',
    pax: 300,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(300, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Ellysa & Amir (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2026-02-14'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Dalily & Fakhrul (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2026-02-14'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Haziq & Hafizah (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2026-02-14'),
    sesi: 'siang',
    pax: 600,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(600, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Nisa & Syazwan Malam (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2026-02-14'),
    sesi: 'malam',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Pika & Iman (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2026-02-15'),
    sesi: 'siang',
    pax: 300,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(300, 'Elham Hall'),
  },

  // ── MARCH 2026 ────────────────────────────────────────────
  {
    nama_majlis: 'Majlis Arissa & Shahrin (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2026-03-28'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_briyani, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis Atila & Aziq (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2026-03-28'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_minyak, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Syikin & Azwa (Asmara Malam)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2026-03-28'),
    sesi: 'malam',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_minyak, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.kacang, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Qaisara & Arif (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2026-03-28'),
    sesi: 'siang',
    pax: 1300,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.kacang, air_panas: STD.teh },
    invoice: buildInvoice(1300, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Aqilah & Aliff (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2026-03-29'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_minyak, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.kacang, air_panas: STD.kopi },
    invoice: buildInvoice(500, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Akmar & Afiq (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2026-03-29'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.pencuk, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Juwita Hall'),
  },

  // ── APRIL 2026 ────────────────────────────────────────────
  {
    nama_majlis: 'Majlis Adam & Umai (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2026-04-04'),
    sesi: 'siang',
    pax: 800,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    remarks: 'Majlis gabung',
    invoice: buildInvoice(800, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Putri & Amri (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2026-04-04'),
    sesi: 'siang',
    pax: 300,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(300, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Suzzlin & Farid (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2026-04-05'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Nasir & Syahirah (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2026-04-11'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Juwita Hall'),
  },
  // Apr 11-12 events from invoices
  {
    nama_majlis: 'Majlis 11 Apr (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2026-04-11'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis 12 Apr (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2026-04-12'),
    sesi: 'siang',
    pax: 1300,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1300, 'Elham Hall', [{ desc: 'Laksa Penang', qty: 400, price: 3.5 }]),
  },
  {
    nama_majlis: 'Majlis 12 Apr (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2026-04-12'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Diyanah & Alif (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2026-04-18'),
    sesi: 'siang',
    pax: 1500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1500, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Suhana & Rusyaidi (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2026-04-18'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis Alya & Hamizan (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2026-04-19'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis Afiq & Alesya (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2026-04-25'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Asmara Hall'),
  },

  // ── MAY 2026 (before 9 May) ───────────────────────────────
  {
    nama_majlis: 'Majlis 2 Mei (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2026-05-02'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis 2 Mei (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2026-05-02'),
    sesi: 'siang',
    pax: 500,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(500, 'Juwita Hall'),
  },
  {
    nama_majlis: 'Majlis 2 Mei (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2026-05-02'),
    sesi: 'siang',
    pax: 650,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(650, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis 2 Mei Malam (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2026-05-02'),
    sesi: 'malam',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Asmara Hall'),
  },
  {
    nama_majlis: 'Majlis 3 Mei (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2026-05-03'),
    sesi: 'siang',
    pax: 700,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(700, 'Juwita Hall', [{ desc: 'Laksa Penang', qty: 500, price: 3.5 }]),
  },
  {
    nama_majlis: 'Majlis 3 Mei (Elham)',
    hall_name: 'Elham Hall',
    tarikh: new Date('2026-05-03'),
    sesi: 'siang',
    pax: 1000,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(1000, 'Elham Hall'),
  },
  {
    nama_majlis: 'Majlis 3 Mei (Asmara)',
    hall_name: 'Asmara Hall',
    tarikh: new Date('2026-05-03'),
    sesi: 'siang',
    pax: 400,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    invoice: buildInvoice(400, 'Asmara Hall', [{ desc: 'Makan Beradab', qty: 1, price: 100 }, { desc: 'Laksa Penang', qty: 100, price: 3.5 }]),
  },
  {
    nama_majlis: 'Majlis 4 Mei (Juwita)',
    hall_name: 'Juwita Hall',
    tarikh: new Date('2026-05-04'),
    sesi: 'siang',
    pax: 120,
    status: 'completed',
    menu_selection: { nasi: STD.nasi_briyani, ayam: STD.ayam, daging: STD.daging_hitam, acar: STD.paceri, bubur: STD.pulut, air_panas: STD.teh },
    remarks: 'Menu kampung',
    invoice: {
      line_items: [
        { description: 'Juwita Event Hall — Menu Kampung', qty: 120, unit_price: 15 }
      ],
      gaji_pekerja: 100,
      berkat: 0
    },
  },
]
